name = "vlog-control-room"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "vlog-control-room-db"
database_id = "b70c6b73-979f-46d5-8fdf-a671d34f6742"

[[kv_namespaces]]
binding = "CACHE"
id = "3acc30fb49c94cca9c4a550b735ef64f"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "vlog-control-room-assets"

[ai]
binding = "AI"
